# Generated by Django 3.1.7 on 2021-04-04 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210404_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downvote',
            name='created',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='created',
        ),
    ]
