# Generated by Django 3.1.7 on 2021-04-05 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210404_2134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
