# Generated by Django 3.1.7 on 2021-04-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_delete_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downvote',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='upvote',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
