# Generated by Django 3.1.7 on 2021-04-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210405_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downvote',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
